### ISSUE TITLE
OData version 3.0 onward not supported

### ISSUE THREAD

**Issue by jnolis** [fsprojects/FSharp.Data.TypeProviders#10]
I have a API I am trying to connect to that uses OData version 3.0, and the F# type provider doesn't seem to work with it. Since OData is now to version 4, it seems like some updating should be done.

```
open FSharp.Data.TypeProviders
FSharp.Data.TypeProviders.ODataService<[URL FOR ODATA 3.0]>
```

It seems to be discussed on this stack overflow page

http://stackoverflow.com/questions/20906533/webapi2-odata-f-type-provider

**Comment by theimowski** [comment]
ping, any plans on updating OData type provider to version 4?

**Comment by dsyme** [comment]
@theimowski People seem to be moving rapidly to the Swagger type provider.  Is that an alternative for you? https://github.com/fsprojects/SwaggerProvider

See also https://github.com/caindy/ODataTypeProvider

**Comment by forki** [comment]
OData is still the only api that some Microsoft products expose. AFAIK swagger is not really helping here.

**Comment by dsyme** [comment]
> OData is still the only api that some Microsoft products expose. AFAIK swagger is not really helping here.

I would be very happy to see an updated OData provider.  I think it should be rewritten from scratch though, as an erasing type provider.

**Comment by theimowski** [comment]
My use case is for internal project - would like to property-based test OData api (which is implemented on top of Web Api). Don't know too much about those 2 web tech, but from initial research it looks like it should be possible to add a Swagger definition using Swashbuckle for a Web Api project.
However not yet sure how it could deal with the OData protocol.

**Comment by tpetricek** [comment]
I spent a bit of type looking at this when working on the pivot type provider in The Gamma. It turns out that the OData v4 spec has [OData extensions for data aggregation](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html), which looks very close to the kinds of thing you can write using the pivot type provider - the only reason why I did not use OData in the end was that it looks quite complicated (probably for good reasons) and I couldn't find many services that actually expose data via this format. (Aside from some MS and SAP products...)

**Comment by buvinghausen** [comment]
Swagger is great for API documentation but it is completely and totally useless at letting the user build up their own queries against the properties in the response document as well as filtering out or selectively filtering the fields in the response that they want.  That's where OData tends to shine...

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/
